### ISSUE TITLE
Executing Shortcut doesn't produce any visible output

### ISSUE THREAD

**Issue by artman41** [wslutilities/wslu#141]
**Background Information:**
 - Build: 19041
 - WSL: Fedora 31 (Custom Built)
```
[artman41@DESKTOP-TQGCI07 bin ]$ cat /etc/redhat-release
Fedora release 31 (Thirty One)
```
```
[artman41@DESKTOP-TQGCI07 bin ]$ rpm -q kernel
kernel-5.6.8-200.fc31.x86_64
kernel-5.7.9-100.fc31.x86_64
kernel-5.7.15-100.fc31.x86_64
```
```
[artman41@DESKTOP-TQGCI07 bin ]$ uname -r
4.19.84-microsoft-standard  
```
 - Version: 3.2.0 
```
[artman41@DESKTOP-TQGCI07 bin ]$ yum list installed | grep wslu
wslu.noarch                                  3.2.0-1                             @copr:copr.fedorainfracloud.org:wslutilities:wslu   
```

**Describe the bug**
Executing the created Shortcut shows the Windows Hourglass cursor for a brief second before returning to the default Cursor. No other actions happen.

**To Reproduce**

- Create Shortcut
```
[artman41@DESKTOP-TQGCI07 bin ]$ wslusc -i `pwd`/idea.png -g `pwd`/idea.sh
[info] You choose to use custom icon: /home/artman41/idea/current/bin/idea.png. Processing...
[info] Converting png icon to ico...
[info] Create shortcut idea.sh.lnk successful    
```
![image](https://user-images.githubusercontent.com/5568965/90918786-2ff3b600-e3dd-11ea-838b-415681c5ea08.png)

- Execute Shortcut

**Expected behavior**
Application to load via X11 similar to a native app

**Additional context**
- This was tested in response to #138 being fixed in v3.2.0 (Environment has not changed since raising the issue)
- Executing `idea.sh` from the terminal loads the GUI as expected, whereas the shortcut doesn't have any visible effect
- Other applications such as `gedit` load when ran from the terminal but not when executed via shortcut

The 'target' of the shortcut is as follows
```
C:\Windows\System32\wscript.exe C:\\Users\\Tyler\wslu\runHidden.vbs C:\\\\\\Windows\\System32\\wsl.exe -d fedora -d fedora -e  /usr/share/wslu/wslusc-helper.sh "/home/artman41/idea/idea-IC-202.6397.94/bin/idea.sh "
```

**Comment by gerardvt** [comment]
Same issue here.

Further testing shows that the bug is due to the wsluc-helper.sh script setting the wrong value for the DISPLAY environment variable.

On the test system, the correct value for DISPLAY (resulting in 172.22.112.1:0.0 in my case) is obtained by:
wsl2_d_tmp="$(grep nameserver /etc/resolv.conf | awk '{print $2}')"
export DISPLAY=${wsl2_d_tmp}:0

However the script erroneously sets the DISPLAY (resulting in 192.168.43.50:0.0 in my case) value by using the lines in the script:
set +H
wsl2_d_tmp="$(eval "$ipconfig_exec" | grep -n -m 1 "Default Gateway.*: [0-9a-z]" | cut -d : -f 1)"
wsl2_d_tmp="$(eval "$ipconfig_exec" | sed $(( wsl2_d_tmp - 4 ))','$(( wsl2_d_tmp + 0 ))'!d' | grep IPv4 | cut -d : -f 2 | sed -e "s|\s||g" -e "s|\r||g")"
set -H
export DISPLAY=${wsl2_d_tmp}:0.0

A quick hack to get the script to work is to cut and paste the following two lines just before the last 2  lines in  the script  (i.e. lines "cd ~ || exit" and "bash -l -c "$*"):
wsl2_d_tmp="$(grep nameserver /etc/resolv.conf | awk '{print $2}')"
export DISPLAY=${wsl2_d_tmp}:0

**Comment by gerardvt** [comment]
Did not pursue further debugging to test why wrong path in script is being selected in setting the DISPLAY env var.

**Comment by patrick330602** [comment]
Hi @artman41 ,
Can you try to remove ~/.config/wslu folder? I will try to make a quick patch.

Hi @gerardvt ,
what system language you are using? Thanks

**Comment by gerardvt** [comment]
Just referring to wsluc-helper.sh bash script installed as part of wslutilities on ubuntu 20.04 wsl 2

**Comment by patrick330602** [comment]
@gerardvt Just to confirm, do you install the PPA version or the version that in the main?

**Comment by gerardvt** [comment]
Sorry I was not clear. I installed wslu via apt on ubuntu 20.04. Version details below.

$> apt-cache policy wslu
wslu:
  Installed: 3.1.1-1
  Candidate: 3.1.1-1
  Version table:
 *** 3.1.1-1 500
        500 https://access.patrickwu.space/wslu/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
     2.3.6-0ubuntu2~20.04.0 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     2.3.6-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages

**Comment by patrick330602** [comment]
@artman41 I have fixed and the fix will be available for 3.2.1
@gerardvt Please use the Ubuntu official PPA insteadfor the latest release: https://launchpad.net/~wslutilities/+archive/ubuntu/wslu

**Comment by romanlex** [comment]
@patrick330602 when are you planning to release 3.2.1? 😊

**Comment by patrick330602** [comment]
@romanlex There is a blocking bug I am currently fixing, hopefully it will be fixed today
