### ISSUE TITLE
Is PowerShell necessary for wslview?

### ISSUE THREAD

**Issue by archiif** [wslutilities/wslu#197]
Are there any advantages over just calling `cmd.exe /c start "" "$lname"` or `explorer.exe "$lname"` in `wslview`? I'm asking this because the launch time of PowerShell kind of sucks on my slow system, which is annoying when you're trying to open links frequently from inside WSL.

**Comment by patrick330602** [comment]
Unfortunately, both options are not well supported. `cmd.exe` will have issues with the absolute Linux path (due to cmd not supporting UNC path) and `explorer.exe` have an issue (https://github.com/microsoft/WSL/issues/6565).

I am currently thinking about providing the alternative engines for `wslview` in the future version.
