### ISSUE TITLE
/usr/share/wslu/conf should be /etc/wslu/conf

### ISSUE THREAD

**Issue by tranzystorek-io** [wslutilities/wslu#241]
The typical location for the global package config files is `/etc/...,`
From a package maintainer standpoint it feels weird to be installing the conf file to `/usr/share/wslu/`.

Also the conf file has a screaming "DO NOT EDIT" warning, but I can't see the reasoning? Usually the /etc/ config files for linux packages have root as owner, but that doesn't mean they can't be changed ever, only that it's an operation reserved for system administrators (or copied over to user-specific locations ofc).

**Comment by patrick330602** [comment]
Thank you for the feedback, I do see your point, however:
1.  Change the location will break the existing installation (there are people who use the packages since canary versions);
2. several default settings are stored in this file so I am not expecting users to edit this file.

So in this case, what I can do this:
1. Offer file in both locations; and
2. remove the DO NOT EDIT lines in the `/etc` one.

However, due to the things pile up in my daily job, I try to get it in 4.0.1 in the coming weeks. Hope you could understand.

**Comment by tranzystorek-io** [comment]
Thanks for the answer! Absolutely take your time with this, no pressure 😄

I'm wondering what would the precedence be for merging various configs, e.g. /etc/ -> /usr/share/ -> $HOME/.config and so on?

**Comment by patrick330602** [comment]
Right now: `/usr/share/wslu/conf -> /usr/share/wslu/custom.conf ->  $HOME/.config/wslu/conf -> $HOME/.wslurc`;
After this fix: `/usr/share/wslu/conf -> /usr/share/wslu/custom.conf -> /etc/wslu/conf -> /etc/wslu/custom.conf ->  $HOME/.config/wslu/conf -> $HOME/.wslurc`
