### ISSUE TITLE
input url will not invoke error which caused issue

### ISSUE THREAD

**Issue by patrick330602** [wslutilities/wslu#256]
> Originally reoported on https://github.com/wslutilities/wslu/pull/243 and https://github.com/wslutilities/wslu/pull/244#discussion_r976161863 by @crossing

`wslpath -w ` is not return error for url now; instead, it throws a interesting badly encoded string like the following:

```
 $ wslpath -w https://google.com
https\google.com
```

**Comment by marveloo** [comment]
I think this behaviour of `wslpath` is intentional. I would guess this is related the fact that Windows does not support colon characters in file names, therefore, they translate colons into something else to maintain interoperability.

Example:
```sh
$ mkdir "https:"
$ echo "Hello!" > "https://google.com"
$ cat "https://google.com"
Hello!
$ notepad.exe "$(wslpath -w "https://google.com")"
```
Notepad opens the file with its contents just fine here.
