### ISSUE TITLE
generated shortcuts open in a second (additional) window on taskbar  in win10

### ISSUE THREAD

**Issue by hltdev8642** [wslutilities/wslu#67]
When I create shortcuts using **wslusc** , if pinning them to the taskbar the following occurs:

![InkedAnnotation 2019-04-24 071828_LI](https://user-images.githubusercontent.com/39349712/56655977-414e7600-6662-11e9-9661-5653f5735993.jpg)

If you try to pin the second icon, it ends up turning into the xserver application icon (x410 in my case), which results in this:

![Annotation 2019-04-24 072910](https://user-images.githubusercontent.com/39349712/56656142-b28e2900-6662-11e9-903a-1ce6c15ecbce.png)

Hope someone knows the solution, and I imagine it could also be an issue with x410 or pengwin, so the issue may need to be posted there instead (sorry if thats so!)

Thanks
Jared

**Comment by patrick330602** [comment]
This is a limitation of WSL and it is expected. when running the shortcut, it will use your Windows X server(X410, VcXsrv, Xming, etc) to create a separate window for displaying the Linux app. Since it is displaying in another app, window for displaying app will be separated from the original shortcut.

**Comment by patrick330602** [comment]
This question is now in the Wiki --> FAQ section.

**Comment by hltdev8642** [comment]
thank you for the quick response, it would be great if someone could find a workaround but I'll survive :-]
